### PR TITLE
Add new Thor option to allow old style of always prompting for the fo…

### PR DESCRIPTION
**Pull request by Jimrnelson**
…lder to be deployed.

### CODE REVIEW

**Comment by Jimrnelson** [comment]
Yes, that's in the options page in Thor.  

The default value to the option is .F. which means that unless somebody changes it there, they will get the behavior that you recently installed.  In fact, I am likely to be the only one who ever will use this option (essentially, choosing the option is the old way).

The caption for the checkbox appears in the class that is defined at the end of the Thor tool.

**Comment by lscheffler** [comment]
I think you should fix the ` ValidateThisFolder(Curdir())` problem in your code. It does nothing because it is coded wrong, and will only make up new misunderstandings. Just remove the part if you don't want it.

And I can not see why you force yourself to click folders until you get the folder with the .git subfolder. If you just use `validate` instead of `ValidateThisFolder` you get your *home* - top level in git terms - just by clicking any folder in your structure. It ends up on the same folder, only
- more elegant
- and you can by sure it's a git repo and not some folder
  - there is even no need to have the gitfolder inside your repository, this is just an assumption as the name *.git*. It could be anywhere, as long as you have file access. Open bash, enter `git help init` and look up *--separate-git-dir*. git clone owns this parameter too. There is a lot of half wisdom out there, I can't help it. Mostly tips by GUI users who never understand what they are doing. Next to folks thinking github is git. (shudder)

If you need to click the toplevel folder, at least get git toplevel folder as in validate, and compare with your folder, you even can run it through validate, because the toplevel is the return - or empty. Validate keeps the recent  folder. But please, not this *.git* thing. It's embarrassing.
 
----
> Yes, that's in the options page in Thor.

Sry, what exactly is in what settings where in Thor? To set that per user, to set all per user? The whole thing is not that easy to understand, I tend to ignore it.

**Comment by lscheffler** [comment]
Jim, there is only a suggestion.   

You say you have an IDE with many projects (pjx) open, and like to process one of those.
I assume, your projects are scattered around, and each is on a distinct repository, but *within* this repository.

So, the most simple and most fast solution would be (using my code):
Use your switch to turn off the initial *validate for the current folder*. It will automatically look up activeproject, and return it's top level folder.   
It will ask you if it is the right structure/project. If not, just answer "No", and pick the folder you like, or cancel out.

I assume, you will process the project you are working with.  
But basically you just need to set the right pjx active, and you are done. Just click "Yes"

For that you have a simple solution if your recent folder is inside a repository, but not the repository you need, move fast to your target and can still pick any repository.

This would be a great thing, because it keeps full flexibility and speed.

**Comment by lscheffler** [comment]
Ok, so far. The question was, is this per user (windows logon) or per environment (foxuser).

If I change on this place for BeautifyX, it's per environment, what renders it rather useless. It's a pain to set all of this stuff on a lower ten projects on all comps ...

It might not be a problem, but one never knows.

**Comment by lscheffler** [comment]
@Jimrnelson Would you mind to fix out the reintroduced `ValidateThisFolder(Curdir())` bug and push again?

I have some changes in the cue. I can publish them for merge, but then the work to merge will end up on your side. I fear, it's less work if I merge yours. And I see no need in a merge race.

**Comment by Jimrnelson** [comment]
> Ok, so far. The question was, is this per user (windows logon) or per environment (foxuser).
> 
> If I change on this place for BeautifyX, it's per environment, what renders it rather useless. It's a pain to set all of this stuff on a lower ten projects on all comps ...
> 
> It might not be a problem, but one never knows.

BeautifyX pre-dates Thor and the values for its options are controlled within PEMEditor, which uses a file in Home(7).  There are  a few other tools that use that same file.

The rest of Thor tools use a file in Thor's Table folder for their options settings.

**Comment by lscheffler** [comment]
That is odd, because Home(7) would mean I get the same settings for each project - what I do not see. But I can dive into this myself. It's only the horror of PEMEditor. ;)

So the *regular* Thor settings are for anybody accessing the same folder.

I need to think about this. Your setting (or my suggestion on https://github.com/VFPX/VFPXDeployment/pull/18#issuecomment-1570519803) make some sense for some of my projects - but not for all.

**Comment by Jimrnelson** [comment]
> It's only the horror of PEMEditor. ;)

Yes, I have to agree, the horror of PEMEditor internals.   

As my first VFPX project, I have to say it's truly byzantine.

It would be so much easier if it only delivered its original purpose (editing PEMs) without having so many other Thor tools embedded in it.

**Comment by lscheffler** [comment]
The ValidateThisFolder(Curdir()) does nothing, or only in some rare circumstances. It never worked with me, that's why I replaced it with FULLPATH the first place. Looking up the toplevel folder was second. Anyway, if you like to pick a folder all the time, it might create surprising results.   
So it is a kind of a bug, and I do think one should not re-introduce one.   
The next coworker will run through it, fix it for it's *intended* work like me, and you end up the same.

CURDIR() is a error-prone function working like CD on CMD level, where CD will not change the drive. You know like
```
C:
CD \Muh
#now we are on C:\Muh
CD D:\Mie
#we are still on C:\Muh, but D: will address D:\Mie; D:somefile expands to D:\Mie\somefile
```
The most cheap way to get current folder is FULLPATH("") If you like the code to start with work-on-current-folder technique, you should replace CURDIR() with FULLPATH(""). Else, remove it, please.

**Comment by lscheffler** [comment]
> > It's only the horror of PEMEditor. ;)
> 
> Yes, I have to agree, the horror of PEMEditor internals.
> 
> As my first VFPX project, I have to say it's truly byzantine.
> 
> It would be so much easier if it only delivered its original purpose (editing PEMs) without having so many other Thor tools embedded in it.

Yeah, it looks like a grown up swiss army knife. Any way, a great tool.

**Comment by Jimrnelson** [comment]
> The ValidateThisFolder(Curdir()) does nothing, or only in some rare circumstances. It never worked with me, that's why I replaced it with FULLPATH the first place. Looking up the toplevel folder was second. Anyway, if you like to pick a folder all the time, it might create surprising results. So it is a kind of a bug, and I do think one should not re-introduce one. The next coworker will run through it, fix it for it's _intended_ work like me, and you end up the same.
> 
> CURDIR() is a error-prone function working like CD on CMD level, where CD will not change the drive. You know like
> 
> ```
> C:
> CD \Muh
> #now we are on C:\Muh
> CD D:\Mie
> #we are still on C:\Muh, but D: will address D:\Mie; D:somefile expands to D:\Mie\somefile
> ```
> 
> The most cheap way to get current folder is FULLPATH("") If you like the code to start with work-on-current-folder technique, you should replace CURDIR() with FULLPATH(""). Else, remove it, please.

@lscheffler 

Actually, I don't care about the reference to CurDir() at all, since my choice of the VFPX project to deploy is never related in any way to my current directory.  That was Doug's code, I obviously can't say whether it's relevant to him.

However, I have no time to make any further changes to this before next week (at the earliest), so I recommend once again to simply leave that code as is.  It can be addressed at some other time.

**Comment by lscheffler** [comment]
@DougHennig, you introduced to idea to use the current folder for a target. Since the code is not working as intended, please clarify (just check the boxes, multiple is fine)
- [ ] It never worked, kick it out
- [ ] It should engage only if the current folder is a git top level folder
- [ ] If the current folder is within a repository, use this repository
- [ ] Just ignore it, try the active project (Jim's option off)
- [ ] Just ignore it, pick a folder (Jim's option on)

And, please, merge I will do the work. :(

**Comment by Jimrnelson** [comment]
> If the current folder is within a repository, use this repository

This option will never work for me.  My current folder is always within a repository, but that repository will never be the one I will want to deploy..

FWIW, my intent for my option is to truly ALWAYS prompt for the folder, no exceptions.  The leftover code for CurDir does not matter to me one way or another.

**Comment by lscheffler** [comment]
Would you mind to switch to LevelExtreme PM?

**Comment by lscheffler** [comment]
Yes, UT is renamed to [LevelExtreme](https://www.levelextreme.com), quiet, but still there. Any way to expose a mail will do too. 

Because it's non technical.

**Comment by DougHennig** [comment]
@lscheffler The intention is that if the current folder contains a repository (in my normal operation, having a .git subdirectory), then use that folder. Otherwise, ask the user.

**Comment by lscheffler** [comment]
@DougHennig, so for that part, we keep it as it is. 
- If within a repository, change to the toplevel folder (where normal people will find the gitfolder *.git*) and run from there. If not, try other stuff.
- If Jims option is turned on, it goes straight for GETDIR.

**Pull request merged**
